### ISSUE TITLE
2.0.6 breaks the CLI!

### ISSUE THREAD

**Issue by swashcap** [HenrikJoreteg/templatizer#108]
### Bug

templatizer’s v2.0.6 contains a breaking change to the CLI functionality. Running the bin results in an error message:

```shell
$ node_modules/.bin/templatizer
: No such file or directory
```

This should output the [`usage` info](https://github.com/HenrikJoreteg/templatizer/blob/bcd768107f75588079eb1f05463cd527de4bfa07/bin/cli#L14-L27). CLI use with `-d` and `-o` flags produces the same error message.

### Environment

* Templatizer: **2.0.6**
* NPM: **4.5.0**
* Node.js: **7.9.0**
* OS: **Ubuntu 14.04**

Related: #107

**Comment by swashcap** [comment]
Similar response on OS X (10.12.4) with the same NPM && Node.js:

```shell
$ node_modules/.bin/templatizer
env: node\r: No such file or directory
```

Ruh roh! Seeing the same thing with Node.js@6.10.2 and npm@3.10.10.

**Comment by swashcap** [comment]
A little web search revealed nwjs-community/nw-builder#75, which indicates that a bad line ending on _bin/cli_’s shebang line messes up the `env` lookup. A little inspection reveals this _somehow_ changed between 2.0.5 and 2.0.6:

```shell
$ npm i templatizer@2.0.6
# Install...
$ file node_modules/templatizer/bin/cli 
node_modules/templatizer/bin/cli: a /usr/bin/env node script text executable, ASCII text, with CRLF line terminators
$ npm i templatizer@2.0.5
# Install...
$ file node_modules/templatizer/bin/cli 
node_modules/templatizer/bin/cli: a /usr/bin/env node script text executable, ASCII text
```

Indeed, when I manually change the line endings in _node_modules/templatizer/bin/cli _ everything works. I assume git modifies line endings when cloning repositories, which is why I was unable to reproduce when I cloned this repository directly.

Now, how to fix the issue…

**Comment by HenrikJoreteg** [comment]
@swashcap thanks for digging into this, also @gdibble can you help out here? I've got my hands completely full right now.

**Comment by gdibble** [comment]
Thanks @swashcap.
Yep @HenrikJoreteg, planning to debug tonight when I'm available.

**Comment by HenrikJoreteg** [comment]
Thanks @gdibble. @swashcap in the meantime if you haven't already, you could certainly hardcode your app to `2.0.5` in your dependencies.

**Comment by gdibble** [comment]
There were a lot of dependencies updated before I bumped the version. While I have not seen this in my dev or production environments, I will test several OS's and plan to narrow down the module-update cause.

**Comment by swashcap** [comment]
@HenrikJoreteg Yeah, pinning to `2.0.5` seems like the best solution.

@gdibble I believe its last package publish occurred on a Windows machine, which modified the executable shebang line to:

```
- #!/usr/bin/env node\n
+ #!/usr/bin/env node\r\n
```

This change wouldn't be tracked by git because it figures out line endings for the OS automatically. The new line endings were pushed to npm with the 2.0.6 publish (that `ASCII text, with CRLF line terminators` above). Sounds like this is an ongoing npm issue (see npm/npm#13203). You’ll likely have to creating tooling (maybe fires a `precommit` bin test?) that ensures no bad line endings. The NWJS folks used an _.editorconfig_ file to this end, but not every editor acknowledges it.

**Comment by gdibble** [comment]
@swashcap I was able to debug the issue and found the `esprima@^3.0.0` module update is what broke us. I retested the CLI commands on Mac OS X and Windows 10 and no longer had the issue. Therefore I pushed a v2.0.7 to help. Let me know if you still have issues after the update. Thanks!
