### ISSUE TITLE
Consider adding an option to build each template into its own file.

### ISSUE THREAD

**Issue by HenrikJoreteg** [HenrikJoreteg/templatizer#17]
If this is a feature anyone wants... +1 it. Thanks.

**Comment by newtriks** [comment]
+1

**Comment by capricube** [comment]
+1 ... especially in development mode

**Comment by lukekarrys** [comment]
@newtriks @capricube Can either of you expand of the reason for needing this? I've never seen the need for it myself, but that doesn't mean it's not worthwhile. :smile: I'd be interested in adding support if there is something I'm overlooking here (which is very likely).

**Comment by lukekarrys** [comment]
Closing this old issue since this likely won't get added. I recommend something like https://github.com/domenic/jadeify for requiring single template files.
