### ISSUE TITLE
Ability to include a mixin but not have it transformed in every included file

### ISSUE THREAD

**Issue by lukekarrys** [HenrikJoreteg/templatizer#39]
I've found a case where the AST transform mixin feature creates some unnecessary code.

Most of the time if a mixin is part of a jade file, it gets pulled out into its own function which makes everything great and modular. But in the following scenario...

**./mixins.jade** This file is only a mixin and gets generated at `templates.mixins.generic()`
``` jade
mixin generic()
  p 123
```

But if I want to use the `generic` mixin in multiple files like this via jade's `include`:

**./file1.jade**
``` jade
include mixins
div.file1
  mixin generic()
```

**./file2.jade**
``` jade
include mixins
span.file2
  mixin generic()
```

Then templatizer will generate a function for `file1.generic()` and `file2.generic()`. It'd be nice if there was some way to know if the mixin was coming from an included file, in which case templatizer wouldn't pull out the mixin.

Anyway, I'll probably take a stab at this but wanted to write out my reasoning first.

**Comment by ngryman** [comment]
:+1:

**Comment by jblanche** [comment]
:+1:

**Comment by capricube** [comment]
:+1:  i also consider this a really useful feature. recently i started to use https://github.com/kizu/bemto with my jade templates. When using templatizer the mixin gets included into every generated AMD module. Because of the mixins weight the modules grow considerably. 

It would be great to generate mixins into separate modules and include them where needed. Can someone point me the right direction where to start? Or is there already an implementation available?

**Comment by lukekarrys** [comment]
@capricube Unfortunately there isn't an implementation for this yet. It will require some changes to the AST parsing code for tenplatizer. I'm not sure when I'll get to this but I would gladly accept any PRs for this functionality.

**Comment by capricube** [comment]
Alright i'll dig into it. Could you provide any hints where to start?

**Comment by lukekarrys** [comment]
Templatizer currently uses [`lib/transformMixins.js`](https://github.com/HenrikJoreteg/templatizer/blob/master/lib/transformMixins.js#L143-L147) to take mixin calls from the jade template and add them onto the parent namespace of the templatizer object.

I haven't inspected the Jade output to see if it looks different when the mixin is included via the `include` statement, but if it is then the code could detect those differences and not have it transform those mixins.
