### ISSUE TITLE
Update Jade dependency.

### ISSUE THREAD

**Issue by ngryman** [HenrikJoreteg/templatizer#76]
Hey,

I would really need to use a feature introduced in Jade [1.8.0](/jadejs/jade/blob/master/History.md#180--2014-11-28). Could you bump your dependency version?

Thanks!

**Comment by lukekarrys** [comment]
Hey @ngryman, the jade version is specified with a semver range which is currently set to `^1.7.0`, so the version `1.8.0` should satisfy that. If I do an `npm install templatizer` and then run `npm ls` this is what I get:

```
$ npm ls --depth 1
temp@1.0.0 /Users/lukekarrys/Desktop/temp
└─┬ templatizer@1.1.1
  ├── escodegen@0.0.26
  ├── esprima@1.2.3
  ├── falafel@0.3.1
  ├── jade@1.9.1
  ├── minimist@0.1.0
  ├── uglify-js@2.4.16
  ├── underscore@1.7.0
  └── walkdir@0.0.7
```

If you're in an existing project, I think you can fix this by running `npm update templatizer`. Let me know if that works for you.

**Comment by ngryman** [comment]
Exact! Thanks you.
My bad, sorry for the inconvenience.

**Comment by lukekarrys** [comment]
No inconvenience at all @ngryman! Glad you got it sorted out :smile:
