### ISSUE TITLE
Respect Glob when giving one 

### ISSUE THREAD

**Issue by jblanche** [HenrikJoreteg/templatizer#79]
With a structure like 
```
|- templates
   |- component1
   |  |- index.jade
   |  |- component1.jade
   |
   |- component2
      |- index.jade
      |- component2.jade
```
When giving a blob with restrictions like `'/templates/**/!(index).jade'` that is supposed to take all but the `index.jade` files under the templates directory, Templatizer looks for files matching the pattern, add the corresponding folders to the ones to deal with and compile all the files in them, even the one restricted by the blob (here `index.jade`).

**Comment by lukekarrys** [comment]
Closed by #82
