### ISSUE TITLE
How to integrate templatizer with i18n ?

### ISSUE THREAD

**Issue by skotchio** [HenrikJoreteg/templatizer#81]
I've just started to use https://github.com/mashpie/i18n-node in my jade view pages. Now I want to move using i18n to possible work with templatizer. How could I do it?

**Comment by lukekarrys** [comment]
Hey @skotchio, thanks for the issue.

I'm not really sure how well `templatizer` and `i18n-node` would play together. Templatizer is built to take jade files and compile them into a JS file that can be used client-side. I've never used `i18n-node` before but it looks like a server-side only solution to i18n, so I'm not sure how it would be configured to work with templatizer.

Sorry for the unhelpful answer. Please reopen if I'm misunderstanding the problem or if you find some way to make them work together.

**Comment by skotchio** [comment]
@lukekarrys thanks for the answer. I've switched to https://github.com/i18next/i18next instead that supports client-side. Unfortunately I'm exploring this module yet and can give you feedback later.
