### ISSUE TITLE
TypeError: Cannot read property 'body' of undefined error when using mixins

### ISSUE THREAD

**Issue by judepoole** [HenrikJoreteg/templatizer#83]
When using mixins I am seeing this error:

tmp1/templatizer/lib/transformMixins.js:98
        mixinStatements = node.expression.right.body.body;
                                                    ^
TypeError: Cannot read property 'body' of undefined

This is using node version v0.10.26 (tried under os x and linux)

cloning the repo and running the tests yields the same error, so it doesn't seem to be specific to my code.  I can provide my templates if necessary, though.

> templatizer@1.5.0 copy-runtime /home/jude/dev/tmp1/templatizer
> cp node_modules/jade/lib/runtime.js jaderuntime.js

/home/jude/dev/tmp1/templatizer/lib/transformMixins.js:98
        mixinStatements = node.expression.right.body.body;
                                                    ^
TypeError: Cannot read property 'body' of undefined
    at findAndReplaceMixin (/home/jude/dev/tmp1/templatizer/lib/transformMixins.js:98:53)
    at /home/jude/dev/tmp1/templatizer/lib/transformMixins.js:144:21
    at walk (/home/jude/dev/tmp1/templatizer/node_modules/falafel/index.js:60:9)
    at /home/jude/dev/tmp1/templatizer/node_modules/falafel/index.js:51:25
    at Array.forEach (native)
    at forEach (/home/jude/dev/tmp1/templatizer/node_modules/falafel/index.js:8:31)
    at /home/jude/dev/tmp1/templatizer/node_modules/falafel/index.js:49:17
    at Array.forEach (native)
    at forEach (/home/jude/dev/tmp1/templatizer/node_modules/falafel/index.js:8:31)
    at walk (/home/jude/dev/tmp1/templatizer/node_modules/falafel/index.js:44:9

**Comment by lukekarrys** [comment]
Thanks for the report. It looks like a jade update broke our AST parsing so it won't work with the latest 1.11.x version. I'll take a look at this as soon as I can. In the meantime you should be able to pin jade to 1.9.2 by installing that first to your project with `npm install jade@1.9.2 --save` and then install templatizer. 

---------
Luke Karrys

**Comment by judepoole** [comment]
Pinning jade as suggested worked.  Thanks for the quick response!

**Comment by lukekarrys** [comment]
Version 1.10.0 works also so I'm pinning that version of jade until I have time to fix the AST parsing of mixins.
