### ISSUE TITLE
Two templates with same name in different directories throw an error

### ISSUE THREAD

**Issue by schatekar** [HenrikJoreteg/templatizer#87]
I have following directory structure

```javascript
views
   - mixins
      -editProfile.jade
      <other mixins>
   - editProfile.jade //This is at view level now
```

When I run templatizer for the above, I get following exception

```shell
                    throw new Error(item + ' from ' + templateDirectory + path
                          ^
Error: editProfile.jade from views\mixins\editProfile.jade already exists in views\editProfile.jade
    at node_modules\templatizer\templatizer.js:137:27
    at Array.forEach (native)
    at node_modules\templatizer\templatizer.js:115:41
    at arrayEach (node_modules\templatizer\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (node_modules\templatizer\node_modules\lodash\index.js:3345:13)
    at baseWrapperValue (node_modules\templatizer\node_modules\lodash\index.js:2768:30)
    at LodashWrapper.wrapperValue (node_modules\templatizer\node_modules\lodash\index.js:6124:14)
    at module.exports (node_modules\templatizer\templatizer.js:144:5)
```

Is there anyway to have multiple jade templates with same name in different locations?

**Comment by schatekar** [comment]
I have managed to fix this by making following two changes

1. Stop recursive walking of files using `walkdir` and only go one level deep. This is done by passing option `{no_recurse: true}`
2. Change the key of `_readTemplates` hash from the file name to the full path. 

If above is acceptable, I am happy to submit a PR

**Comment by schatekar** [comment]
I was too quick to put a comment. After making above changes, I am getting following error

```shell
\node_modules\templatizer\lib\transformMixins.js:68
ression.callee.property.value || node.expression.callee.object.property.value;
                                                                       ^
TypeError: Cannot read property 'value' of undefined
    at transformMixinCalls (\node_modules\templatizer\lib\transformMixins.js:68:100)
```

I believe this is to do with one of my templates rather than the change I made to templatizer. Can someone confirm?

**Comment by lukekarrys** [comment]
@schatekar Can you post the code that you are using to call `templatizer`? From the looks of the directory structure you posted, it should work (depending on your options) to have files named the same in different directories. I think this should work:

```
templatizer('views/`, outputPath)
```

It doesn't look necessary in your case to use the globbing options, and that might be whats causing the error.

`templatizer` puts nested templates on an object so if you are running it on your `views` directory you should have on template at `templatizer.editProfile` and one at `templatizer.mixins.editProfile`. So we're already kind of doing what you suggested in above and using the whole path for the path of the template.

**Comment by schatekar** [comment]
@lukekarrys  You are right that I am using globe paths like below

```javascript
templatizer(__dirname + '/../views/**/*.jade', 
			__dirname + '/../public/javascripts/templates.js', 
			{
				dontRemoveMixins: true,
				inlineJadeRuntime: false
				});
```

But again, the reason for doing so was that when I used `__dirname + '/../views'`, none of the templates were transformed.

**Comment by lukekarrys** [comment]
When you say none of the templates were transformed, do you mean that they didn't appear in the built `templates.js` file? Or the error from #88 was thrown?

If it was the error from #88, then that was a side effect of using dynamic mixiins and you should try again with `dontTransformMixins: true`.

Here's the code I was able to get to work on my computer:

```
.
├── node_modules
│   └── templatizer
├── package.json
├── public
│   └── templates.js # after running node server/buildTemplates.js
├── server
│   └── buildTemplates.js
└── views
    ├── editProfile.jade
    └── mixins
        └── editProfile.jade
```

And **buildTemplates.js** looks like this:
```js
var templatizer = require('templatizer');
templatizer(__dirname + '/../views', __dirname + '/../public/templates.js', {
    dontRemoveMixins: true,
    inlineJadeRuntime: false
});
```

which works to create a file at `public/templates.js`.

Can you try something like that in your setup and see if that works?

**Comment by lukekarrys** [comment]
I'm going to close this as I can't recreate the error, but let me know if it is still causing an issue for you.

**Comment by schatekar** [comment]
@lukekarrys Apologies it took me time to revert. After upgrading to latest version and removing glob path, it works fine.
