### ISSUE TITLE
@lukekarrys/jade-runtime no longer exists in NPM

### ISSUE THREAD

**Issue by suitupalex** [HenrikJoreteg/templatizer#92]
It looks like @lukekarrys's version of the jade-runtime has disappeared from npm and his Github. Doing an install on anything pulling templatizer in is throwing an error due to lack of the dependency.

**Comment by lukekarrys** [comment]
@suitupalex I'm still seeing it here: https://www.npmjs.com/package/@lukekarrys/jade-runtime, although I never put it up on GitHub.

What happens if you `npm install @lukekarrys/jade-runtime`? Note you might need to update `npm` to get support for namespaced packages.

**Comment by lukekarrys** [comment]
It looks like you'll need at least `npm@2.7.0` or greater to use scoped packages https://docs.npmjs.com/getting-started/scoped-packages#update-npm-and-log-in

**Comment by suitupalex** [comment]
Oh that's it. Our CI tool is pulling in an older npm. Thanks for the quick reply!

**Comment by lukekarrys** [comment]
No problem, I've run into that issue before. :smile:
