### ISSUE TITLE
Uncaught Error: Module name "@lukekarrys/jade-runtime" has not been loaded yet for context: _. Use require([])

### ISSUE THREAD

**Issue by happilymarrieddad** [HenrikJoreteg/templatizer#96]
I get this really weird error after I've complied and I try to include the templates file. I'm using 1.5.4 but I wanted to upgrade to 2.03 and this is what happened when I did. I added the require.js CDN because it said require was not defined. Thanks!

```
script(type='text/javascript',src='//cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js')
script(type='text/javascript',src='/js/templates.js')
```

**Comment by lukekarrys** [comment]
The global and AMD builds have been removed in v2 (see [the changelog](https://github.com/HenrikJoreteg/templatizer#changelog) for more details). There are some links in the changelog for different ways to get the same functionality using some other utilities. Although if v1.5.4 is working for you, there might not be much reason to upgrade to v2 (it was mostly released to make development and future maintenance easier).
