### ISSUE TITLE
Any plans to update to work with pug?

### ISSUE THREAD

**Issue by lastobelus** [HenrikJoreteg/templatizer#97]
Now that jade has been [re-christened](https://github.com/pugjs/pug)...

Bonus points if you rename to **puglatizer**.

**Comment by lukekarrys** [comment]
No plans currently, but that's mostly because I'm not using this as much as I used to.

I also haven't stayed up to date on the `pug` changes so I wasn't sure how much would need to change (or if the new APIs were considered stable yet). There's some AST parsing going on in this project which would almost definitely need to be rewritten if the compiled output from `pug` is different than `jade`.

I'd be up for accepting PRs and/or adding anyone as a contributor who wanted to take on these changes 😄

**Comment by lastobelus** [comment]
my current use was just for a tiny bit of tooling, which itself was only marginally justified by the budget for what I was tasked to accomplish ¯\_(ツ)_/¯

**Comment by wamoyo** [comment]
D'oh : ( I loved this approach. Jade templates on the client side, super fast. Too good to be true.

**Comment by happilymarrieddad** [comment]
Can I try to tackle pug? I still use templatizer for one of our production servers and I would love to migrate to pug instead of jade!

**Comment by lukekarrys** [comment]
@happilymarrieddad Go for it!

**Comment by happilymarrieddad** [comment]
@lukekarrys Hey man, I just finished the prototype. I need to push it up one my branch and pull it in normally to make sure it works right. I just did the npm pack thingy and then npm install ./templatizer-2.0.4.tgz   and it worked great.

**Comment by lukekarrys** [comment]
@happilymarrieddad If you do a PR to this project, it will run the test suite on travis to make sure everything passes. It'd be nice add some tests too to make sure things work with pug.

If the changes aren't backwards compatible, then we'd have to release as a new major version on npm (I'd be happy to add you as a contributor too and give publish rights on npm once everthing is working on your branch).

**Comment by happilymarrieddad** [comment]
I think I'm going to try and write a separate one. It's too complicated I think to handle both jade and pug in the same tool.

**Comment by lukekarrys** [comment]
@happilymarrieddad  :+1: I'd be happy to link to it from this project once it's done!

**Comment by wamoyo** [comment]
@happilymarrieddad thanks for putting in the time and effort : ) I'll be using your version.

**Comment by happilymarrieddad** [comment]
@lukekarrys thanks man!
@wamoyo hey man thanks. It's probably going to be a day or two to be honest because I have a lot to finish at work but I'm going to start tonight.

**Comment by wamoyo** [comment]
@happilymarrieddad No rush at all. Let me know if I can help with testing or something.

**Comment by happilymarrieddad** [comment]
@wamoyo 
@lukekarrys 
@lastobelus 

Introduction... TADA! Puglatizer! 
https://github.com/happilymarrieddad/puglatizer
https://www.npmjs.com/package/puglatizer

**Comment by lukekarrys** [comment]
Thanks @happilymarrieddad! I added a link in the readme to it. 😄

Now that it's released and mentioned in the readme (and templatizer probably wont be updated) I think I'm going to close this issue. Thanks again for your work on this!

**Comment by wamoyo** [comment]
@happilymarrieddad Thanks so much!!
